# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for hannah configurations
Name: jolla-configuration-hannah
Requires:
- patterns-sailfish-device-configuration-hannah

Summary: Jolla Configuration hannah

